### ISSUE TITLE
Use @@locale or _locale?

### ISSUE THREAD

**Issue by donny-dont** [alan-knight/polymer_intl#1]
From https://github.com/googlei18n/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#global-attributes it seems like it should be

```
{
  "@@locale": "fr",
  ...
}
```

**Comment by donny-dont** [comment]
Actually tested using `@@locale` and that doesn't seem to work. Guessing bug in intl then @alan-knight ?

**Comment by alan-knight** [comment]
Yes, it seems like it. I don't know if that changed in ARB, or if it was wrong in the first place. And Google Translation Toolkit doesn't even seem to emit it, which is the only independent source I know of that writes these.

**Comment by alan-knight** [comment]
Switched to use @@locale.

**Comment by alan-knight** [comment]
But now I switched away from it in favor of using something closer to what Google Translator Toolkit produces. So it does infer from the file names when regenerated.
